{
 "title": "Operation Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "operationName",
    "label": "Operation Name (Graph & Heatmap)",
    "query": { "query": "operation_duration_count" }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Operation Count",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_count[$__range]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "All Operation Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_bucket[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$operationName Operation Count Graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_bucket{operationName=\"$operationName\"}[1m]))",
     "legendFormat": "{{$operationName}}"
    }
   ]
  },
  {
   "title": "$operationName Operation Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_bucket{operationName=\"$operationName\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "All Operation Count Graph",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_count[1m]))",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Operation Duration Percentile",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(operation_duration_bucket[$__range])) by (le,operationName))",
     "legendFormat": "Median"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(operation_duration_bucket[$__range])) by (le,operationName))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(operation_duration_bucket[$__range])) by (le,operationName))",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "Operation Count",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(operation_duration_count[$__range])) by (operationName)",
     "legendFormat": "{{operationName}}"
    }
   ]
  }
 ]
}