version: '3'

services:
  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:2888

  kafka:
    image: wurstmeister/kafka:2.12-2.4.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: >
        post_events:1:1
    depends_on:
      - zookeeper
