scrape_configs:
  - job_name: graphql
    scrape_interval: 1s
    static_configs:
      - targets:
          - localhost:4000
        labels:
          group: gateway

  - job_name: node
    scrape_interval: 1s
    static_configs:
      - targets:
          - localhost:9100
